var first_name="Raina";
var last_name="Agarwal";
var fullname=first_name.concat(last_name);
console.log(fullname);
var a=3;
var b=2;
var add=a+b;
console.log(add);
var sub=a-b;
console.log (sub);
